[package]
name = "cortexa"
version = "0.0.0"
edition = "2024"
license = "MIT"
description = "General purpose neurons to experiment with"

[dependencies]
ndarray = "0.17.2"
ndarray-rand = "0.16.0"
rand = "0.10.0"
